export enum DoacaoCategoria {
    SAUDE = "SAUDE",
    ALIMENTAR = "ALIMENTAR",
    HABITACIONAL = "HABITACIONAL",
    VESTIMENTA = "VESTIMENTA",
    VETERINARIA = "VETERINARIA",
    MOVEIS = "VETERINARIA",
    OUTROS = "OUTROS"
}
